; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitm-1

[env]
platform = espressif32
framework = arduino
build_type = release
monitor_speed = 115200
extra_scripts = pre:scripts/embed_visualizer.py
build_unflags = 
	-g
	-ggdb
	-ggdb3
	-Og
build_flags = 
	-D CORE_DEBUG_LEVEL=0
	-D NDEBUG
	-Os
	-D CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
	-D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
	-D CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Wl,--strip-all
lib_deps =
	knolleary/PubSubClient @ ^2.8
	links2004/WebSockets @ ^2.7.2
	adafruit/Adafruit NeoPixel @ ^1.12.3
	h2zero/NimBLE-Arduino @ ^1.4.3

[env:esp32-s3-devkitm-1]
board = esp32-s3-devkitm-1
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = dio_opi
build_flags = 
	${env.build_flags}
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D ESPWAVERIDER_USB_CONSOLE=0

[env:esp32-s3-devkitm-1-usb-console]
board = esp32-s3-devkitm-1
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = dio_opi
build_flags = 
	${env.build_flags}
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D ESPWAVERIDER_USB_CONSOLE=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32dev-uart1]
board = esp32dev
upload_speed = 460800
board_build.partitions = huge_app.csv
build_flags = 
	${env.build_flags}
	-D ESPWAVERIDER_BOARD_ESP32_GENERIC_UART1

[env:heltec-wifi-lora-32-v3]
board = heltec_wifi_lora_32_V3
upload_speed = 460800
board_build.partitions = huge_app.csv
build_flags = 
	${env.build_flags}
	-D ESPWAVERIDER_BOARD_HELTEC_WIFI_LORA_32_V3

[env:heltec-wifi-lora-32-v4]
board = heltec_wifi_lora_32_V3
upload_speed = 460800
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
	${env.build_flags}
	-D ESPWAVERIDER_BOARD_HELTEC_WIFI_LORA_32_V4