[workspace]
members = [
  "crates/espwaverider-core",
  "firmware/esp32s3",
]
default-members = [
  "crates/espwaverider-core",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
publish = false
rust-version = "1.88"

[workspace.dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[patch.crates-io]
esp-radio = { path = "vendor/esp-radio" }

[patch."https://github.com/esp-rs/mbedtls-rs"]
mbedtls-rs = { path = "vendor/mbedtls-rs/mbedtls-rs" }
mbedtls-rs-sys = { path = "vendor/mbedtls-rs/mbedtls-rs-sys" }

