#pragma once

#include <Arduino.h>

struct BoardProfile {
  const char* key;
  const char* displayName;
  const char* manufacturer;
  const char* radarModel;
  uint32_t usbBaud;
  uint32_t radarBaud;
  uint8_t radarSerialPort;
  int radarRxPin;
  int radarTxPin;
  int radarPresencePin;
  uint8_t radarPresencePinMode;
  int statusRgbLedPin;
  uint8_t statusRgbLedCount;
  bool hasStatusRgbLed;
};

#if defined(ESPWAVERIDER_BOARD_HELTEC_WIFI_LORA_32_V4)
#define ESPWAVERIDER_DEFAULT_BOARD_KEY "heltec-wifi-lora-32-v4"
#define ESPWAVERIDER_DEFAULT_BOARD_NAME "Heltec WiFi LoRa 32 V4"
#define ESPWAVERIDER_DEFAULT_BOARD_MANUFACTURER "Heltec"
#define ESPWAVERIDER_DEFAULT_RADAR_MODEL "HLK-LD2420"
#define ESPWAVERIDER_DEFAULT_USB_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_SERIAL_PORT 1
#define ESPWAVERIDER_DEFAULT_RADAR_RX_PIN 2
#define ESPWAVERIDER_DEFAULT_RADAR_TX_PIN 3
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN 4
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN_MODE INPUT
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_PIN -1
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_COUNT 0
#define ESPWAVERIDER_DEFAULT_HAS_STATUS_RGB_LED false
#elif defined(ESPWAVERIDER_BOARD_HELTEC_WIFI_LORA_32_V3)
#define ESPWAVERIDER_DEFAULT_BOARD_KEY "heltec-wifi-lora-32-v3"
#define ESPWAVERIDER_DEFAULT_BOARD_NAME "Heltec WiFi LoRa 32 V3"
#define ESPWAVERIDER_DEFAULT_BOARD_MANUFACTURER "Heltec"
#define ESPWAVERIDER_DEFAULT_RADAR_MODEL "HLK-LD2420"
#define ESPWAVERIDER_DEFAULT_USB_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_SERIAL_PORT 1
#define ESPWAVERIDER_DEFAULT_RADAR_RX_PIN 4
#define ESPWAVERIDER_DEFAULT_RADAR_TX_PIN 5
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN 6
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN_MODE INPUT
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_PIN -1
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_COUNT 0
#define ESPWAVERIDER_DEFAULT_HAS_STATUS_RGB_LED false
#elif defined(ESPWAVERIDER_BOARD_ESP32_GENERIC_UART1)
#define ESPWAVERIDER_DEFAULT_BOARD_KEY "esp32-generic-uart1"
#define ESPWAVERIDER_DEFAULT_BOARD_NAME "ESP32 Generic UART1"
#define ESPWAVERIDER_DEFAULT_BOARD_MANUFACTURER "Espressif"
#define ESPWAVERIDER_DEFAULT_RADAR_MODEL "HLK-LD2420"
#define ESPWAVERIDER_DEFAULT_USB_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_SERIAL_PORT 1
#define ESPWAVERIDER_DEFAULT_RADAR_RX_PIN 16
#define ESPWAVERIDER_DEFAULT_RADAR_TX_PIN 17
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN 18
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN_MODE INPUT
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_PIN -1
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_COUNT 0
#define ESPWAVERIDER_DEFAULT_HAS_STATUS_RGB_LED false
#else
#define ESPWAVERIDER_DEFAULT_BOARD_KEY "esp32-s3-devkitm-1"
#define ESPWAVERIDER_DEFAULT_BOARD_NAME "ESP32-S3 DevKitM-1"
#define ESPWAVERIDER_DEFAULT_BOARD_MANUFACTURER "Espressif"
#define ESPWAVERIDER_DEFAULT_RADAR_MODEL "HLK-LD2420"
#define ESPWAVERIDER_DEFAULT_USB_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_BAUD 115200
#define ESPWAVERIDER_DEFAULT_RADAR_SERIAL_PORT 1
#define ESPWAVERIDER_DEFAULT_RADAR_RX_PIN 4
#define ESPWAVERIDER_DEFAULT_RADAR_TX_PIN 5
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN 6
#define ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN_MODE INPUT_PULLDOWN
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_PIN 48
#define ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_COUNT 1
#define ESPWAVERIDER_DEFAULT_HAS_STATUS_RGB_LED true
#endif

#if __has_include("board_user_config.h")
#include "board_user_config.h"
#endif

#ifndef ESPWAVERIDER_BOARD_KEY
#define ESPWAVERIDER_BOARD_KEY ESPWAVERIDER_DEFAULT_BOARD_KEY
#endif

#ifndef ESPWAVERIDER_BOARD_NAME
#define ESPWAVERIDER_BOARD_NAME ESPWAVERIDER_DEFAULT_BOARD_NAME
#endif

#ifndef ESPWAVERIDER_BOARD_MANUFACTURER
#define ESPWAVERIDER_BOARD_MANUFACTURER ESPWAVERIDER_DEFAULT_BOARD_MANUFACTURER
#endif

#ifndef ESPWAVERIDER_RADAR_MODEL
#define ESPWAVERIDER_RADAR_MODEL ESPWAVERIDER_DEFAULT_RADAR_MODEL
#endif

#ifndef ESPWAVERIDER_USB_BAUD
#define ESPWAVERIDER_USB_BAUD ESPWAVERIDER_DEFAULT_USB_BAUD
#endif

#ifndef ESPWAVERIDER_RADAR_BAUD
#define ESPWAVERIDER_RADAR_BAUD ESPWAVERIDER_DEFAULT_RADAR_BAUD
#endif

#ifndef ESPWAVERIDER_RADAR_SERIAL_PORT
#define ESPWAVERIDER_RADAR_SERIAL_PORT ESPWAVERIDER_DEFAULT_RADAR_SERIAL_PORT
#endif

#ifndef ESPWAVERIDER_RADAR_RX_PIN
#define ESPWAVERIDER_RADAR_RX_PIN ESPWAVERIDER_DEFAULT_RADAR_RX_PIN
#endif

#ifndef ESPWAVERIDER_RADAR_TX_PIN
#define ESPWAVERIDER_RADAR_TX_PIN ESPWAVERIDER_DEFAULT_RADAR_TX_PIN
#endif

#ifndef ESPWAVERIDER_RADAR_PRESENCE_PIN
#define ESPWAVERIDER_RADAR_PRESENCE_PIN ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN
#endif

#ifndef ESPWAVERIDER_RADAR_PRESENCE_PIN_MODE
#define ESPWAVERIDER_RADAR_PRESENCE_PIN_MODE ESPWAVERIDER_DEFAULT_RADAR_PRESENCE_PIN_MODE
#endif

#ifndef ESPWAVERIDER_STATUS_RGB_LED_PIN
#define ESPWAVERIDER_STATUS_RGB_LED_PIN ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_PIN
#endif

#ifndef ESPWAVERIDER_STATUS_RGB_LED_COUNT
#define ESPWAVERIDER_STATUS_RGB_LED_COUNT ESPWAVERIDER_DEFAULT_STATUS_RGB_LED_COUNT
#endif

#ifndef ESPWAVERIDER_HAS_STATUS_RGB_LED
#define ESPWAVERIDER_HAS_STATUS_RGB_LED ESPWAVERIDER_DEFAULT_HAS_STATUS_RGB_LED
#endif

static constexpr BoardProfile kBoardProfile{
  ESPWAVERIDER_BOARD_KEY,
  ESPWAVERIDER_BOARD_NAME,
  ESPWAVERIDER_BOARD_MANUFACTURER,
  ESPWAVERIDER_RADAR_MODEL,
  ESPWAVERIDER_USB_BAUD,
  ESPWAVERIDER_RADAR_BAUD,
  ESPWAVERIDER_RADAR_SERIAL_PORT,
  ESPWAVERIDER_RADAR_RX_PIN,
  ESPWAVERIDER_RADAR_TX_PIN,
  ESPWAVERIDER_RADAR_PRESENCE_PIN,
  ESPWAVERIDER_RADAR_PRESENCE_PIN_MODE,
  ESPWAVERIDER_STATUS_RGB_LED_PIN,
  ESPWAVERIDER_STATUS_RGB_LED_COUNT,
  ESPWAVERIDER_HAS_STATUS_RGB_LED,
};